-- Bayern und Baden-Württemberg Kennzeichen hinzufügen
INSERT INTO license_plates (code, city, district, state) VALUES

  -- ══════════════════════════════════════════
  -- BAYERN
  -- ══════════════════════════════════════════

  -- Kreisfreie Städte
  ('A',   'Augsburg',                'Augsburg',                   'Bayern'),
  ('AM',  'Amberg',                  'Amberg',                     'Bayern'),
  ('AN',  'Ansbach',                 'Ansbach',                    'Bayern'),
  ('AS',  'Amberg-Sulzbach',         'Amberg-Sulzbach',            'Bayern'),
  ('BA',  'Bamberg',                 'Bamberg',                    'Bayern'),
  ('BT',  'Bayreuth',                'Bayreuth',                   'Bayern'),
  ('CO',  'Coburg',                  'Coburg',                     'Bayern'),
  ('ER',  'Erlangen',                'Erlangen',                   'Bayern'),
  ('FÜ',  'Fürth',                   'Fürth',                      'Bayern'),
  ('IN',  'Ingolstadt',              'Ingolstadt',                 'Bayern'),
  ('KE',  'Kempten (Allgäu)',        'Kempten (Allgäu)',           'Bayern'),
  ('KFB', 'Kaufbeuren',              'Kaufbeuren',                 'Bayern'),
  ('LA',  'Landshut',                'Landshut',                   'Bayern'),
  ('M',   'München',                 'München',                    'Bayern'),
  ('MM',  'Memmingen',               'Memmingen',                  'Bayern'),
  ('N',   'Nürnberg',                'Nürnberg',                   'Bayern'),
  ('PA',  'Passau',                  'Passau',                     'Bayern'),
  ('R',   'Regensburg',              'Regensburg',                 'Bayern'),
  ('RO',  'Rosenheim',               'Rosenheim',                  'Bayern'),
  ('SC',  'Schwabach',               'Schwabach',                  'Bayern'),
  ('SR',  'Straubing',               'Straubing',                  'Bayern'),
  ('SW',  'Schweinfurt',             'Schweinfurt',                'Bayern'),
  ('WEN', 'Weiden i.d.OPf.',         'Weiden in der Oberpfalz',   'Bayern'),
  ('WÜ',  'Würzburg',                'Würzburg',                   'Bayern'),

  -- Landkreise
  ('AB',  'Aschaffenburg',           'Aschaffenburg',              'Bayern'),
  ('AIC', 'Aichach',                 'Aichach-Friedberg',          'Bayern'),
  ('AÖ',  'Altötting',               'Altötting',                  'Bayern'),
  ('BGL', 'Berchtesgaden',           'Berchtesgadener Land',       'Bayern'),
  ('CHA', 'Cham',                    'Cham',                       'Bayern'),
  ('DAH', 'Dachau',                  'Dachau',                     'Bayern'),
  ('DGF', 'Dingolfing',              'Dingolfing-Landau',          'Bayern'),
  ('DLG', 'Dillingen a.d.Donau',     'Dillingen a.d.Donau',       'Bayern'),
  ('DON', 'Donauwörth',              'Donau-Ries',                 'Bayern'),
  ('EBE', 'Ebersberg',               'Ebersberg',                  'Bayern'),
  ('ED',  'Erding',                  'Erding',                     'Bayern'),
  ('EI',  'Eichstätt',               'Eichstätt',                  'Bayern'),
  ('ERH', 'Herzogenaurach',          'Erlangen-Höchstadt',         'Bayern'),
  ('FFB', 'Fürstenfeldbruck',        'Fürstenfeldbruck',           'Bayern'),
  ('FO',  'Forchheim',               'Forchheim',                  'Bayern'),
  ('FRG', 'Freyung',                 'Freyung-Grafenau',           'Bayern'),
  ('FS',  'Freising',                'Freising',                   'Bayern'),
  ('GAP', 'Garmisch-Partenkirchen',  'Garmisch-Partenkirchen',     'Bayern'),
  ('GUN', 'Günzburg',                'Günzburg',                   'Bayern'),
  ('HAS', 'Haßfurt',                 'Haßberge',                   'Bayern'),
  ('HO',  'Hof',                     'Hof',                        'Bayern'),
  ('KEH', 'Kelheim',                 'Kelheim',                    'Bayern'),
  ('KG',  'Bad Kissingen',           'Bad Kissingen',              'Bayern'),
  ('KU',  'Kulmbach',                'Kulmbach',                   'Bayern'),
  ('LAU', 'Lauf a.d.Pegnitz',        'Nürnberger Land',            'Bayern'),
  ('LI',  'Lindau (Bodensee)',        'Lindau (Bodensee)',          'Bayern'),
  ('LIF', 'Lichtenfels',             'Lichtenfels',                'Bayern'),
  ('LL',  'Landsberg a.Lech',        'Landsberg am Lech',          'Bayern'),
  ('MB',  'Miesbach',                'Miesbach',                   'Bayern'),
  ('MIL', 'Miltenberg',              'Miltenberg',                 'Bayern'),
  ('MN',  'Mindelheim',              'Unterallgäu',                'Bayern'),
  ('MSP', 'Karlstadt',               'Main-Spessart',              'Bayern'),
  ('ND',  'Neuburg a.d.Donau',       'Neuburg-Schrobenhausen',     'Bayern'),
  ('NEA', 'Neustadt a.d.Aisch',      'Neustadt a.d.Aisch-Bad Windsheim', 'Bayern'),
  ('NES', 'Bad Neustadt a.d.Saale',  'Rhön-Grabfeld',              'Bayern'),
  ('NEW', 'Neustadt a.d.Waldnaab',   'Neustadt a.d.Waldnaab',      'Bayern'),
  ('NM',  'Neumarkt i.d.OPf.',       'Neumarkt in der Oberpfalz',  'Bayern'),
  ('NU',  'Neu-Ulm',                 'Neu-Ulm',                    'Bayern'),
  ('OA',  'Sonthofen',               'Oberallgäu',                 'Bayern'),
  ('OAL', 'Marktoberdorf',           'Ostallgäu',                  'Bayern'),
  ('PAF', 'Pfaffenhofen a.d.Ilm',    'Pfaffenhofen a.d.Ilm',       'Bayern'),
  ('PAN', 'Pfarrkirchen',            'Rottal-Inn',                  'Bayern'),
  ('REG', 'Regen',                   'Regen',                      'Bayern'),
  ('ROT', 'Roth',                    'Roth',                       'Bayern'),
  ('SAD', 'Schwandorf',              'Schwandorf',                 'Bayern'),
  ('STA', 'Starnberg',               'Starnberg',                  'Bayern'),
  ('TIR', 'Tirschenreuth',           'Tirschenreuth',              'Bayern'),
  ('TÖL', 'Bad Tölz',                'Bad Tölz-Wolfratshausen',    'Bayern'),
  ('TS',  'Traunstein',              'Traunstein',                 'Bayern'),
  ('WM',  'Weilheim i.OB',           'Weilheim-Schongau',          'Bayern'),
  ('WUG', 'Weißenburg i.Bay.',        'Weißenburg-Gunzenhausen',   'Bayern'),
  ('WUN', 'Wunsiedel',               'Wunsiedel i.Fichtelgebirge', 'Bayern'),

  -- ══════════════════════════════════════════
  -- BADEN-WÜRTTEMBERG
  -- ══════════════════════════════════════════

  -- Kreisfreie Städte
  ('BAD', 'Baden-Baden',             'Baden-Baden',                'Baden-Württemberg'),
  ('FR',  'Freiburg im Breisgau',    'Freiburg im Breisgau',       'Baden-Württemberg'),
  ('HD',  'Heidelberg',              'Heidelberg',                 'Baden-Württemberg'),
  ('HN',  'Heilbronn',               'Heilbronn',                  'Baden-Württemberg'),
  ('KA',  'Karlsruhe',               'Karlsruhe',                  'Baden-Württemberg'),
  ('MA',  'Mannheim',                'Mannheim',                   'Baden-Württemberg'),
  ('PF',  'Pforzheim',               'Pforzheim',                  'Baden-Württemberg'),
  ('S',   'Stuttgart',               'Stuttgart',                  'Baden-Württemberg'),
  ('UL',  'Ulm',                     'Ulm',                        'Baden-Württemberg'),

  -- Landkreise
  ('AA',  'Aalen',                   'Ostalbkreis',                'Baden-Württemberg'),
  ('BB',  'Böblingen',               'Böblingen',                  'Baden-Württemberg'),
  ('BL',  'Balingen',                'Zollernalbkreis',            'Baden-Württemberg'),
  ('BR',  'Staufen im Breisgau',     'Breisgau-Hochschwarzwald',  'Baden-Württemberg'),
  ('CW',  'Calw',                    'Calw',                       'Baden-Württemberg'),
  ('EM',  'Emmendingen',             'Emmendingen',                'Baden-Württemberg'),
  ('ES',  'Esslingen am Neckar',     'Esslingen',                  'Baden-Württemberg'),
  ('FDS', 'Freudenstadt',            'Freudenstadt',               'Baden-Württemberg'),
  ('FN',  'Friedrichshafen',         'Bodenseekreis',              'Baden-Württemberg'),
  ('GP',  'Göppingen',               'Göppingen',                  'Baden-Württemberg'),
  ('KN',  'Konstanz',                'Konstanz',                   'Baden-Württemberg'),
  ('KÜN', 'Künzelsau',               'Hohenlohekreis',             'Baden-Württemberg'),
  ('LB',  'Ludwigsburg',             'Ludwigsburg',                'Baden-Württemberg'),
  ('LÖ',  'Lörrach',                 'Lörrach',                    'Baden-Württemberg'),
  ('MOS', 'Mosbach',                 'Neckar-Odenwald-Kreis',      'Baden-Württemberg'),
  ('OG',  'Offenburg',               'Ortenaukreis',               'Baden-Württemberg'),
  ('RA',  'Rastatt',                 'Rastatt',                    'Baden-Württemberg'),
  ('RV',  'Ravensburg',              'Ravensburg',                 'Baden-Württemberg'),
  ('RW',  'Rottweil',                'Rottweil',                   'Baden-Württemberg'),
  ('SHA', 'Schwäbisch Hall',         'Schwäbisch Hall',            'Baden-Württemberg'),
  ('SIG', 'Sigmaringen',             'Sigmaringen',                'Baden-Württemberg'),
  ('TBB', 'Tauberbischofsheim',      'Main-Tauber-Kreis',          'Baden-Württemberg'),
  ('TÜ',  'Tübingen',                'Tübingen',                   'Baden-Württemberg'),
  ('TUT', 'Tuttlingen',              'Tuttlingen',                 'Baden-Württemberg'),
  ('VS',  'Villingen-Schwenningen',  'Schwarzwald-Baar-Kreis',     'Baden-Württemberg'),
  ('WN',  'Waiblingen',              'Rems-Murr-Kreis',            'Baden-Württemberg'),
  ('WT',  'Waldshut-Tiengen',        'Waldshut',                   'Baden-Württemberg')

ON CONFLICT (code) DO NOTHING;
